export enum PayrollEventType {
  EMPLOYEE_HIRED = "EMPLOYEE_HIRED",
  EMPLOYEE_TERMINATED = "EMPLOYEE_TERMINATED",
  SALARY_ADJUSTED = "SALARY_ADJUSTED",
  TIMESHEET_SUBMITTED = "TIMESHEET_SUBMITTED",
  PAYROLL_RUN_STARTED = "PAYROLL_RUN_STARTED",
  PAYROLL_RUN_COMPLETED = "PAYROLL_RUN_COMPLETED",
}
